import Card from "@material-ui/core/Card";
import CardContent from "@material-ui/core/CardContent";
import { withStyles } from "@material-ui/core/styles";
import TextField from "@material-ui/core/TextField";
import Typography from "@material-ui/core/Typography";
import * as React from "react";

import i18n from "../../i18n";
import FormSpacer from "../FormSpacer";
import PageHeader from "../PageHeader";
import Skeleton from "../Skeleton";

interface SeoFormProps {
  description: string;
  descriptionPlaceholder: string;
  disabled?: boolean;
  loading?: boolean;
  storefrontUrl: string;
  title: string;
  titlePlaceholder: string;
  onChange(event: any);
  onClick();
}

const decorate = withStyles(theme => ({
  addressBar: {
    color: "#006621",
    fontSize: "13px",
    lineHeight: "16px",
    marginBottom: "2px",
    overflow: "hidden" as "hidden",
    textOverflow: "ellipsis" as "ellipsis",
    whiteSpace: "nowrap" as "nowrap"
  },
  descriptionBar: {
    color: "#545454",
    fontSize: "13px",
    lineHeight: "18px",
    overflowWrap: "break-word" as "break-word"
  },
  titleBar: {
    color: "#1a0dab",
    cursor: "pointer",
    fontSize: "18px",
    lineHeight: "21px",
    overflowWrap: "break-word" as "break-word",
    textDecoration: "none",
    wordWrap: "break-word" as "break-word"
  }
}));
const SeoForm = decorate<SeoFormProps>(
  ({
    classes,
    description,
    descriptionPlaceholder,
    disabled,
    loading,
    storefrontUrl,
    title,
    titlePlaceholder,
    onChange,
    onClick
  }) => (
    <Card>
      <PageHeader title={i18n.t("Search Engine Preview")} />
      <CardContent>
        <div>
          {loading ? (
            <Skeleton />
          ) : (
            <>
              <Typography className={classes.titleBar} onClick={onClick}>
                {(title || titlePlaceholder).substr(0, 70)}
              </Typography>
              <Typography className={classes.addressBar}>
                {storefrontUrl}
              </Typography>
              <Typography className={classes.descriptionBar}>
                {(description || descriptionPlaceholder).substr(0, 300)}
              </Typography>
            </>
          )}
        </div>
        <FormSpacer />
        <TextField
          fullWidth
          helperText={i18n.t(
            "If empty, the preview shows what will be autogenerated."
          )}
          label={i18n.t("Search engine title")}
          name="seoTitle"
          onChange={onChange}
          value={title.slice(0, 70)}
          disabled={disabled}
        />
        <FormSpacer />
        <TextField
          fullWidth
          helperText={i18n.t(
            "If empty, the preview shows what will be autogenerated."
          )}
          label={i18n.t("Search engine title")}
          onChange={onChange}
          value={description.slice(0, 300)}
          disabled={disabled}
          name="seoDescription"
        />
      </CardContent>
    </Card>
  )
);
export default SeoForm;
